#+title: My Literate Emacs Configuration
#+author: Christian Dijkstra
#+email: chdka@public-files.de
#+startup: noptag indent content
#+todo: DISABLED(d) | ENABLED(e)
#+todo: BUG(b) FEATURE(f) | FIXED(x)
#+tags: @behaviour(b) @ui(u) env_var(v)
#+tags: { issue(i) feature(f) }

* LICENSE
I've chosen GPLv3, because most of the information and snippets I use are also licensed under GPLv3.

#+begin_src emacs-lisp

;; Copyright (C) 2021
;; Christian Dijkstra <chdka@public-files.de>

;; Author: Christian Dijkstra <chdka@public-files.de>
;; Package-requires: ((emacs "27.1"))

;; This file is part of my Emacs configuration

;; This file is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

#+end_src

* Introduction
This is /My Literate Emacs Configuration/.
It is build upon snippets I've found on the web and my personal preference for the functionality of things.

** Needed elisp file
To use this literate configuration I've created a set of elisp functions defined in:

#+include: "~/.config/emacs/chdka-lisp/chdka-literate-config.el" src emacs-lisp :tangle no

This file is part of this repository.

** Usage of the TODO keywords
I've defined two sets of keywords

- DISABLED | ENABLED :: When the value is *DISABLED*, this heading is not tangled / exported to the =chdka-emacs.el= file. Currently there is an issue with this keyword
- BUG FEATURE | FIXED :: When a heading is set to *BUG*, *FEATURE* it is an indicator something has to be corrected, but at this moment I do not know how exactly.

** Usage of the TAGS
I've define a set of tags, which are a controlled vocabulari in this file.
Following is a description of the tags and the meaning for them.

- @behaviour :: the setting here has an effect on the functionality, but is not necessarily visual. e.g. the setting for auto-revert-mode
- @ui :: the setting here has an effect on the user interface, but is not directly a functionality change. e.g. blinking of the cursor
- env_var :: the setting here reads an environment variable which is defined outside of Emacs

The following list is a mutual exclusive list, meaning only one can be selected via the chords =C-c C-q= or =C-c C-c=
- issue :: this indicates an issue which needs to be resolved
- feature :: this is a feature request, e.g. implement / add a package

* Known issues and needed features for this configuration
This section is a summary of known issues and feature requests for this configuration.

** BUG The *DISABLED* state is not inherited to the subheadings :@behaviour:issue:
Currently there is an issue, when a heading has a *DISABLED* state the subheading is still processed, a workaround for this is to add =:tangle no= to the sourcecode block.
This has to be resolved in the function =chdka-lc-tangle-config-file=.

** FIXED Make it possible for a distinction between *WORK* and *PERSONAL* device :env_var:feature:
My agenda functionality is different for my *PERSONAL* environment vs my *WORK* environment.

#+begin_src emacs-lisp :tangle no
(getenv "CHDKA_DEVICE")
#+end_src

#+RESULTS:
: OWN

* /My Literate Configuration/ starts here
Set some defaults prior loading other packages and initialisations.

** Specific settings in MS Windows

*** Map =CAPSLOCK= as an extra =CTRL= key                      :@behaviour:
I've mapped my =CAPSLOCK= as an extra =CTRL= key.
This is implemented via an registry setting described as below

#+begin_example
  Windows Registry Editor Version 5.00
  
  [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Keyboard Layout]
  "Scancode Map"=hex:00,00,00,00,00,00,00,00,02,00,00,00,1d,00,3a,00,00,00,00,00

  ;;  explanation of the codes
  ;
  ;  Windows Registry Editor Version 5.00
  ;
  ; The hex data is in five groups of four bytes:
  ;   00,00,00,00,\    header version (always 00000000)
  ;   00,00,00,00,\    header flags (always 00000000)
  ;   04,00,00,00,\    # of entries (3 in this case) plus a NULL terminator line.
  ;                    Entries are in 2-byte pairs: Key code to send & keyboard key to send it.
  ;                    Each entry is in LSB, MSB order.
  ;   1d,00,3a,00,\    Send LEFT CTRL (0x001d) code when user presses the CAPS LOCK key (0x003a) 
  ;   38,00,1d,00,\    Send LEFT ALT (0x0038) code when user presses the LEFT CTRL key (0x001d) 
  ;   3a,00,38,00,\    Send CAPS LOCK (0x3A) code when user presses the LEFT ALT key (0x0038) 
  ;   00,00,00,00      NULL terminator

  ;[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Keyboard Layout]
  ;"Scancode Map"=hex:00,00,00,00,\
  ;                   00,00,00,00,\
  ;                   04,00,00,00,\
  ;                   1d,00,3a,00,\
  ;                   38,00,1d,00,\
  ;                   3a,00,38,00,\
  ;                   00,00,00,00
#+end_example

** Default system-wide settings in Emacs
In this section some simple default settings which are system-wide for the emacs configuration

*** Set constant if device is my *OWN* or *WORK*                  :env_var:
For this purpose I've created an environment variable =CHDKA_DEVICE= which holds the following values:
- OWN :: this is my personal device / computer / laptop
- WORK :: this is my work laptop

#+begin_src emacs-lisp
(defconst chdka-emacs-const-is-own-device
  (string-suffix-p "OWN" (getenv "CHDKA_DEVICE") t)
  "This pseudo constant indicates if my current configuration is running on my personal device,
or if it is running on my work device")
#+end_src

#+RESULTS:
: chdka-emacs-const-is-own-device

*** Confirm before exiting                                     :@behaviour:

#+begin_src emacs-lisp
(setq-default confirm-kill-emacs 'yes-or-no-p)
#+end_src

#+RESULTS:
: yes-or-no-p

*** Set an alias to y/n                                        :@behaviour:
Enable y/n instead of yes/no

#+begin_src emacs-lisp
;; fset is used vs defalias, fset is global where defalias registered to the loaded file
;; lisp file
;; - [https://www.gnu.org/software/emacs/manual/html_node/elisp/Defining-Functions.html]
;; - [https://www.reddit.com/r/emacs/comments/4fzgdn/what_difference_there_is_between_defalias_and_fset/]
(fset 'yes-or-no-p 'y-or-n-p) 
#+end_src

*** Customization in its own file                              :@behaviour:
Write customization into its own file

#+begin_src emacs-lisp
(setq-default custom-file (expand-file-name "chdka-custom.el" user-emacs-directory))
#+end_src

And load this file

#+begin_src emacs-lisp
(when (file-exists-p custom-file)
  (load custom-file t))
#+end_src

*** Backup and Auto-save settings

**** Assign a backup and auto-save folder             :@behaviour:env_var:
Stop Emacs littering all my folders with backup files and auto-save files.
Assign a folder for them, and use a flat structure

#+begin_src emacs-lisp
(defconst chdka-emacs-const-backup-rootdir 
          (if (getenv "CHDKA_HOME_CACHE")
              (expand-file-name (concat (getenv "CHDKA_HOME_CACHE") "/emacs/backup/"))
            (expand-file-name "~/.cache/emacs/backup/"))
  "Personal Emacs backup root.")

(if (not (file-exists-p chdka-emacs-const-backup-rootdir))
    (make-directory chdka-emacs-const-backup-rootdir t))
(setq-default backup-directory-alist 
              `((".*" . ,chdka-emacs-const-backup-rootdir)))
#+end_src

#+RESULTS:
: ((.* . d:/christian/.cache/emacs/backup/))

#+begin_src emacs-lisp 
(defconst chdka-emacs-const-autosave-rootdir
          (if (getenv "CHDKA_HOME_CACHE")
              (expand-file-name (concat (getenv "CHDKA_HOME_CACHE") "/emacs/auto-save/"))
            (expand-file-name "~/.cache/emacs/auto-save/"))
  "Personal Emacs auto-save root.")

(if (not (file-exists-p chdka-emacs-const-autosave-rootdir))
    (make-directory chdka-emacs-const-autosave-rootdir t))
(setq-default auto-save-file-name-transforms 
              `((".*" ,(file-name-as-directory chdka-emacs-const-autosave-rootdir) t)))

#+end_src

#+RESULTS:
| .* | d:/christian/.cache/emacs/auto-save/ | t |

**** Set the housekeeping for backup and auto-save            :@behaviour:
For the backup activate some setting regarding version and age of those versions

#+begin_src emacs-lisp
(setq-default make-backup-files t    ; backup of a file the first time it is saved
              backup-by-copying t
              version-control t      ; version numbers for backup files
              delete-old-versions t  ; delete old versions silently
              delete-by-moving-to-trash t
              kept-old-versions 6    ; oldest version to keep
              kept-new-versions 9    ; newest version to keep
)
#+end_src

#+RESULTS:
: 9

Set the intervals for writing an auto-save file and the timeout.

#+begin_src emacs-lisp
(setq-default auto-save-default t    ; auto-save every buffer that visits a file
              auto-save-timeout 20   ; number of seconds idle time before auto-save
              auto-save-interval 200 ; number of keystrokes between auto-saves
) 
#+end_src

#+RESULTS:
: 200

*** Buffer settings
**** Auto revert of the buffer                                :@behaviour:
This settings change the behaviour of Emacs when a file is changed

#+begin_src emacs-lisp
(global-auto-revert-mode 1)                   ; auto update buffer if a file changes
(add-hook 'dired-mode-hook 'auto-revert-mode) ; auto refresh dired when file changes
#+end_src

**** Encoding for saving buffer                               :@behaviour:
Write the files in UTF-8 and even in UTF-8-UNIX when possible

#+begin_src emacs-lisp
(setq-default locale-coding-system 'utf-8
              buffer-file-coding-system 'utf-8-unix
	      default-buffer-file-coding-system 'utf-8-unix)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(set-selection-coding-system 'utf-8)
(set-default-coding-systems 'utf-8-unix)
(when (eq system-type 'windows-nt)
  (set-clipboard-coding-system 'utf-16le-dos))
#+end_src

**** Performance issues on Windows when pasting unicode text  :@behaviour:
Sometime when you paste unicode text in Emacs it responds very slow

#+begin_src emacs-lisp
;; https://www.reddit.com/r/emacs/comments/8v4v7o/why_is_emacs_so_slow_on_windows/
;; sometime with pasting unicode text emacs responds very slow.
;; https://emacs.stackexchange.com/questions/33510/unicode-txt-slowness
(when (eq system-type 'windows-nt)
  (setq inhibit-compacting-font-caches t))
#+end_src

**** Show line and column number in the buffer                       :@ui:
Activate the line-numbers and columns in the buffer

#+begin_src emacs-lisp
(setq-default line-number-mode t
              column-number-mode t
              scroll-conservatively 1000
              ring-bell-function 'ignore)
#+end_src

**** Set the tabs                                         :@behaviour:@ui:
Tabs in the buffer

#+begin_src emacs-lisp
(setq-default indent-tabs-mode nil
              tab-with 4
              require-final-newline t)
#+end_src

**** Enable syntax highlighting for all buffers                      :@ui:

#+begin_src emacs-lisp
(global-font-lock-mode t)
#+end_src

**** Show matching parentheses                                       :@ui:

#+begin_src emacs-lisp
(setq show-paren-delay 0)
(show-paren-mode 1)
#+end_src

**** Set a visual indicator if there is a newline or not             :@ui:

#+begin_src emacs-lisp
(setq visual-line-fringe-indicators '(left-curly-arrow right-curly-arrow))
#+end_src

#+RESULTS:
| left-curly-arrow | right-curly-arrow |

*** User Interface
In this section default settings for the user interface

**** A more useful frame title, display filename                     :@ui:
Display the filename of the active buffer in the frame title.

#+begin_src emacs-lisp
(setq-default frame-title-format
	      '((:eval (if (buffer-file-name)
			   (abbreviate-file-name (buffer-file-name))
			 "%b"))))
#+end_src

**** Frame settings for cursor                                       :@ui:
Settings for the cursor.

#+begin_src emacs-lisp
(blink-cursor-mode 1) ; -1 = disabled
#+end_src

#+RESULTS:
: ignore

**** DISABLED Settings for the menu-bar, tool-bar and scroll-bar     :@ui:
Settings for the tool-bar, menu-bar and scroll-bar are already set in my early-init.el.
Therefore this code block is not tangled.

#+begin_src emacs-lisp
(tool-bar-mode -1)  ; -1 = disabled
(menu-bar-mode  1)  ;  1 = enabled
(scroll-bar-mode 1) ;  1 = enabled
#+end_src




** Per packages
*** Org-mode
**** Org-agenda
**** Org-capture
